config/routes.rb
Rails.application.routes.draw do
  resources :images, except: [:show]
  resources :stills_projects, except: [:index, :show]
  resources :motion_projects, except: [:index, :show]
  
  get 'projects', to: 'projects#index'

  resources :portfolios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :projects

  before_save :set_default_nav_title
  after_save :generate_static_page
  before_destroy :delete_static_page

  validates :title, presence: true

  def project_list
    projects.map do |x|
      {
        title: x.title
      }
    end
  end

  private

  def generate_static_page
    StaticPageService.new.generate_portfolio(title.parameterize)
  end

  # TODO: What to do with projects? Should their static pages be deleted, if
  #       so show a warning popup? Then set them to 'unpublished' or something?
  def delete_static_page
    StaticPageService.new.delete_portfolio(title.parameterize)
  end

  def set_default_nav_title
    self.nav_title = title if nav_title.blank?
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:edit, :update, :destroy]

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.all
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit; end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully created.' }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_portfolio
    @portfolio = Portfolio.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def portfolio_params
    params.require(:portfolio).permit(
      :title,
      :nav_title
    )
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.slim
= form_for @portfolio do |f|
  - if @portfolio.errors.any?
    #error_explanation
      h2 = "#{pluralize(@portfolio.errors.count, "error")} prohibited this portfolio from being saved:"
      ul
        - @portfolio.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :nav_title
    = f.text_field :nav_title, class: "form-control"

  .actions.btn-group
    = link_to 'Back', portfolios_path, class: "btn btn-secondary"
    = f.submit class: "btn btn-primary"

app/views/portfolios/edit.html.slim
h1 Editing portfolio

== render 'form'

app/views/portfolios/index.html.slim
h1 Listing Portfolios

table.table
  thead
    tr
      th Title
      th Nav Title
      th Actions

  tbody
    - @portfolios.each do |portfolio|
      tr
        td = portfolio.title
        td = portfolio.nav_title
        td
          .btn-group
            = link_to 'Edit', edit_portfolio_path(portfolio), class: 'btn btn-primary'
            = link_to 'Destroy', portfolio, data: { confirm: 'Are you sure? This will also unpublish any projects assigned to this portfolio (don\'t worry though, the projects won\'t be deleted so you can always publish them again under a different portfolio)' }, method: :delete, class: 'btn btn-danger'

br

= link_to 'New Portfolio', new_portfolio_path, class: 'btn btn-primary'

app/views/portfolios/new.html.slim
h1 New portfolio

== render 'form'