config/routes.rb
Rails.application.routes.draw do
  resources :images, except: [:show]
  resources :stills_projects, except: [:index, :show]
  resources :motion_projects, except: [:index, :show]
  
  get 'projects', to: 'projects#index'

  resources :portfolios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :portfolio, optional: true

  validates :title, presence: true
  validates :type, presence: true

  before_save :set_default_slug
  after_save :generate_static_page
  before_destroy :delete_static_page

  private

  def generate_static_page
    return if portfolio.nil?

    StaticPageService.new.generate_project(
      portfolio.nav_title,
      slug,
      # Should I be create a copy of self to pass here to the cell?
      ProjectFrontEndCell.new(self).call
    )
  end

  def delete_static_page
    return if portfolio.nil?

    StaticPageService.new.delete_project(
      portfolio.nav_title,
      slug
    )
  end

  def set_default_slug
    slug = title if slug.blank?
    self.slug = slug.parameterize
  end
end

app/controllers/projects_controller.rb
# The ProjectsController is only for used for showing an index of
# stills_projects and motion_projects

class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def find_project_edit_path(project)
    return edit_stills_project_path(project) if project.type == 'StillsProject'

    edit_motion_project_path(project)
  end
end

app/views/projects/index.html.slim
h1 Listing Projects

table.table
  thead
    tr
      th Title
      th Type
      th Portfolio
      th Actions

  tbody
    - @projects.each do |project| 
      tr
        td = project.title
        td = project.type.underscore.humanize
        td = project.try(:portfolio).try(:title)
        td
          .btn-group
            = link_to 'Edit', find_project_edit_path(project), class: "btn btn-primary"
            = link_to 'Destroy', project, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger"

br

= link_to 'New Stills Project', new_stills_project_path, class: "btn btn-primary"
'
= link_to 'New Motion Project', new_motion_project_path, class: "btn btn-primary"