config/routes.rb
Rails.application.routes.draw do
  resources :images, except: [:show]
  resources :stills_projects, except: [:index, :show]
  resources :motion_projects, except: [:index, :show]
  
  get 'projects', to: 'projects#index'

  resources :portfolios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stills_project.rb
class StillsProject < Project
  # TODO: Don't like the name of this join table...change?
  has_many :stills_project_images
  has_many :images, through: :stills_project_images
end

app/controllers/stills_projects_controller.rb
class StillsProjectsController < ApplicationController
  before_action :set_stills_project, only: [:edit, :update, :destroy]

  # GET /stills_projects/new
  def new
    @stills_project = StillsProject.new
  end

  # GET /stills_projects/1/edit
  def edit; end

  # POST /stills_projects
  # POST /stills_projects.json
  def create
    @stills_project = StillsProject.new(stills_project_params)

    respond_to do |format|
      if @stills_project.save
        format.html { redirect_to projects_url, notice: 'Stills project was successfully created.' }
        format.json { render :show, status: :created, location: @stills_project }
      else
        format.html { render :new }
        format.json { render json: @stills_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stills_projects/1
  # PATCH/PUT /stills_projects/1.json
  def update
    respond_to do |format|
      if @stills_project.update(stills_project_params)
        format.html { redirect_to projects_url, notice: 'Stills project was successfully updated.' }
        format.json { render :show, status: :ok, location: @stills_project }
      else
        format.html { render :edit }
        format.json { render json: @stills_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stills_projects/1
  # DELETE /stills_projects/1.json
  def destroy
    @stills_project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Stills project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_stills_project
    @stills_project = StillsProject.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def stills_project_params
    params.require(:stills_project).permit(
      :title,
      :description,
      :homepage_feature,
      :slug,
      :portfolio_id,
      image_ids: []
    )
  end
end

app/helpers/stills_projects_helper.rb
module StillsProjectsHelper
end

app/views/stills_projects/_form.html.slim
= form_for @stills_project do |f|
  - if @stills_project.errors.any?
    #error_explanation
      h2 = "#{pluralize(@stills_project.errors.count, "error")} prohibited this stills_project from being saved:"
      ul
        - @stills_project.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control"
  / .form-group
  /   = f.label :homepage_feature
  /   = f.check_box :homepage_feature, class: "form-control"
  .form-group
    = f.label :portfolio_id
    = f.collection_select :portfolio_id, Portfolio.all, :id, :title, { include_blank: 'None' }, class: "form-control"
  .form-group
    = f.label :slug
    = f.text_field :slug, class: "form-control"
  .form-group
    = f.label :images
    = f.collection_select :image_ids, Image.all, :id, :image_identifier, {}, multiple: true, class: "form-control selectpicker"

  .actions.btn-group
    = link_to 'Back', projects_path, class: "btn btn-secondary"
    = f.submit class: "btn btn-primary"

app/views/stills_projects/edit.html.slim
h1 Editing Stills Project

== render 'form'

app/views/stills_projects/new.html.slim
h1 New Stills Project

== render 'form'